//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McTools.Xrm.Connection.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("McTools.Xrm.Connection.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConnectionStringImage1 {
            get {
                object obj = ResourceManager.GetObject("ConnectionStringImage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the wizard is trying to connect to your Microsoft Dynamics CRM organization.
        /// </summary>
        internal static string ConnectionWizard_ConnectingHeaderDescription {
            get {
                return ResourceManager.GetString("ConnectionWizard_ConnectingHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the connection string you want to use to connect to your Microsoft Dynamics CRM organization.
        /// </summary>
        internal static string ConnectionWizard_ConnectionStringConnectionHeaderDescription {
            get {
                return ResourceManager.GetString("ConnectionWizard_ConnectionStringConnectionHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter credentials required to connect to Microsoft Dynamics CRM organization.
        /// </summary>
        internal static string ConnectionWizard_CredentialsHeaderDescription {
            get {
                return ResourceManager.GetString("ConnectionWizard_CredentialsHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the url displayed in the browser when you are connected to your Microsoft Dynamics CRM organization.
        /// </summary>
        internal static string ConnectionWizard_EnterUrlHeaderDescription {
            get {
                return ResourceManager.GetString("ConnectionWizard_EnterUrlHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information have not been validated.
        /// </summary>
        internal static string ConnectionWizard_ErrorHeaderDescription {
            get {
                return ResourceManager.GetString("ConnectionWizard_ErrorHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us to determine if your Microsoft Dynamics CRM deployment is exposed via IFD.
        /// </summary>
        internal static string ConnectionWizard_IfdSelectionHeaderDescription {
            get {
                return ResourceManager.GetString("ConnectionWizard_IfdSelectionHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url you specified does not look like a valid url for an IFD deployment. Please correct the url.
        /// </summary>
        internal static string ConnectionWizard_InvalidIfUrl {
            get {
                return ResourceManager.GetString("ConnectionWizard_InvalidIfUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong timeout value!
        ///
        ///Expected format : HH:mm:ss.
        /// </summary>
        internal static string ConnectionWizard_InvalidTimeoutValue {
            get {
                return ResourceManager.GetString("ConnectionWizard_InvalidTimeoutValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url you specified is invalid!.
        /// </summary>
        internal static string ConnectionWizard_InvalidUrl {
            get {
                return ResourceManager.GetString("ConnectionWizard_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You changed some values that require to test the connection. Would you like to test it now?
        ///
        ///Note that this is required to validate this wizard.
        /// </summary>
        internal static string ConnectionWizard_NeedToTestConnectionAgain {
            get {
                return ResourceManager.GetString("ConnectionWizard_NeedToTestConnectionAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your credentials before trying to connect.
        /// </summary>
        internal static string ConnectionWizard_PleaseEnterCredentials {
            get {
                return ResourceManager.GetString("ConnectionWizard_PleaseEnterCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string ConnectionWizard_QuestionHeaderTitle {
            get {
                return ResourceManager.GetString("ConnectionWizard_QuestionHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information have been validated.
        /// </summary>
        internal static string ConnectionWizard_SuccessHeaderDescription {
            get {
                return ResourceManager.GetString("ConnectionWizard_SuccessHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to determine the organization name based on the information you specified. Please complete the url to add the organization name inside.
        /// </summary>
        internal static string ConnectionWizard_UnableToDetermineOrganization {
            get {
                return ResourceManager.GetString("ConnectionWizard_UnableToDetermineOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to identify organization from url, please review it!.
        /// </summary>
        internal static string ConnectionWizard_UnableToDetermineOrganizationFromUrl {
            get {
                return ResourceManager.GetString("ConnectionWizard_UnableToDetermineOrganizationFromUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string ConnectionWizard_WarningTitle {
            get {
                return ResourceManager.GetString("ConnectionWizard_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_link {
            get {
                object obj = ResourceManager.GetObject("database_link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_0100 {
            get {
                object obj = ResourceManager.GetObject("logo_0100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_0200 {
            get {
                object obj = ResourceManager.GetObject("logo_0200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoDyn365 {
            get {
                object obj = ResourceManager.GetObject("LogoDyn365", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ServicePrincipal {
            get {
                object obj = ResourceManager.GetObject("ServicePrincipal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XTB_HIGHLIGHT_CUSTOM {
            get {
                object obj = ResourceManager.GetObject("XTB_HIGHLIGHT_CUSTOM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XTB_HIGHLIGHT_PRODUCTION {
            get {
                object obj = ResourceManager.GetObject("XTB_HIGHLIGHT_PRODUCTION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XTB_HIGHLIGHT_UAT {
            get {
                object obj = ResourceManager.GetObject("XTB_HIGHLIGHT_UAT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
